const translations = {
    "en": {
        "nav_home": "Home",
        "nav_about": "About Us",
        "breadcrumb_home": "Home",
        "nav_business": "Our Business",
        "nav_sustainability": "Sustainability",
        "nav_news": "Latest News",
        "nav_careers": "Careers",
        "nav_contact": "Contact Us",
        "completed_projects": "Completed Projects",
        "btn_switch_en": "EN",
        "btn_switch_zh": "繁",
        "btn_switch_cn": "简",
        "footer_intro": "Orientfunds Precast Limited was established in 1998, specializing in the production and supply of precast concrete components.",
        "footer_quick_links": "Quick Links",
        "footer_contact_title": "Contact Us",
        "footer_headquarters": "Headquarters:",
        "footer_factory": "Dongguan Factory:",
        "footer_copyright": "Copyright © 2026 Glorious Concrete (Hong Kong) Limited. All Rights Reserved.",
        "hero_title": "Overcome Challenges, Drive Innovation",
        "index_about_title": "About Glorious Concrete",
        "index_about_desc": "Glorious Concrete (H.K.) Limited is a wholly-owned subsidiary of Sun Hung Kai Properties, established in 1979, specializing in providing high-quality concrete and engineering services. For many years, we have provided stable and reliable supply for foundation, civil, building and infrastructure projects, upholding the commitment of 'Building Homes from the Heart', continuously pursuing excellent quality, and creating safe and durable building foundations.",
        "btn_learn_more": "Learn More →",
        "btn_more": "More →",
        "section_projects": "Engineering Projects",
        "section_strength": "Company Strength",
        "strength_title": "We have complete professional capabilities to realize engineering projects that others consider impossible.",
        "index_strength_desc_1": "While others chase trends, we focus on redefining what is possible in construction. From foundation engineering and concrete mix design to eco-friendly materials and construction technologies, we possess deep professional expertise. What truly sets us apart is that we go beyond cement and steel, breaking boundaries with an engineer's mindset.",
        "index_strength_desc_2": "In the era of green buildings and smart cities, we do not just adapt — we proactively shape the future. By combining construction expertise with environmental innovation, and integrating creative problem-solving with efficient execution, we deliver concrete solutions that stand the test of time, from worksites to communities.",
        "stat_years": "Years Experience",
        "stat_projects": "Successful Projects",
        "serve_clients": "Serving Customers",
        "production_volume": "Production Volume (Cubic Meters)",
        "serve_customer": "Customer Satisfaction",
        "cta_title": "Company Strength",
        "cta_desc": "Learn more about our services and projects",
        "btn_contact_us": "Contact Us",
        "about_title": "About Us",
        "about_intro_title": "Company Introduction",
        "about_profile_title": "Company Profile",
        "about_profile_desc": "Orientfunds Precast Limited was established in 1998. Our factory is located in Shatian Town, Dongguan City. It is a wholly-owned enterprise with an investment of over HK$80 million, covering an area of over 80,000 square meters, with natural waterways and convenient water transportation.",
        "about_location_title": "Factory Location",
        "about_location_desc": "The Dongguan factory is 100km from Hong Kong with a complete transportation network. The factory is located at the entrance of Shiziyang, Pearl River. It takes only 6 hours to reach Hong Kong by sea. It takes 2 hours to reach Hong Kong from Huanggang or Man Kam To by land.",
        "about_hongfai_title": "About Orientfunds",
        "about_yongfai_title": "About Glorious",
        "about_hongfai_desc": "Since its establishment in 1998, Orientfunds has focused on high-quality manufacturing and cross-border services. The company established a modern factory in Shatian, Dongguan, built along the water. Its superior geographical location and natural proximity to waterways provide unique advantages for efficient transportation. The factory is only over 100 kilometers from Hong Kong, with a well-developed transportation network. Water transport to Hong Kong takes about 6 hours, and it takes only just over three hours by car via Huanggang, Liantang, or Shenzhen Bay ports. Leveraging this strategic location, Orientfunds can rapidly connect Guangdong and Hong Kong, providing efficient and reliable cross-border supply chain support for its partners.<br><br>Orientfunds possesses comprehensive production and logistics facilities, including a concrete plant, storage yards, sand and gravel warehouses, and ten all-weather production workshops. Even in adverse weather conditions, it can maintain high-efficiency operations, ensuring quality and progress. The factory area is equipped with movable canopies, electric concrete vehicles, and skid steer loaders to enhance production and finishing efficiency. The storage area covers 25,000 square meters and is currently used for storing precast facade elements. The company also has an independent pier capable of handling products weighing over 30 tons and accommodating large vessels. Combined with mature land transportation, this ensures unimpeded transport by both sea and land.",
        "about_yongfai_desc": "Glorious Concrete (H.K.) Limited is a wholly-owned subsidiary of Sun Hung Kai Properties, specializing in providing high-quality concrete and related engineering services. Since its establishment in 1979, Glorious has played an important role in Hong Kong's construction industry with its professional experience and technology, providing stable and reliable concrete supply for foundation, civil, building and infrastructure projects. The company understands construction needs and can provide diversified solutions according to different projects. Upholding the commitment of 'Building Homes from the Heart', Glorious adheres to the belief of 'Overcoming Difficulties, Blazing New Trails', continuously pursuing excellent quality, building solid and durable building foundations, and creating a safe and comfortable living environment.",
        "core_values": "Core Values",
        "facilities": "Facilities",
        "zone_one_title": "Zone One - Main Production of Building Prefabricated Components",
        "zone_one_desc": "Zone one consists of 5 covered workshops, storage yards and concrete batching plant. The 5 covered workshops ensure high quality and on-time production under all weather conditions. We are capable of producing precast products equivalent to 25 building blocks simultaneously, i.e., handling at least 100 sets of molds, with daily production exceeding 700 tons.",
        "zone_two_title": "Zone Two - Segment / Large Precast Products",
        "zone_two_desc": "Zone Two casting yard and storage yard cover 25,000 m². It is equipped with 2 gantry cranes (80T and 50T each). It functions for the production of heavy precast units e.g. segments, large precast beams/columns and facades, noise barrier panels etc.",
        "jetty_title": "Jetty",
        "jetty_desc": "Our jetty can take in barge over 10,000 tons. There are 2 sets of fixed cranes (150T and 80T), convenient for loading large precast components.",
        "tech_advantage_title": "Technical Advantage",
        "tech_advantage_desc": "Regular Precast Workshops held with remarkable institutes (e.g. HKU, PolyU) and organizations.",
        "business_products_title": "Products",
        "prod_mic": "MiC Modular Integrated Construction",
        "prod_wall_panel": "Lightweight Concrete Wall Panel",
        "prod_facade": "Façade",
        "prod_steel_mic": "Steel MiC",
        "prod_conc_mic": "Concrete MiC",
        "prod_stair": "Staircase",
        "prod_balcony": "Balcony",
        "prod_ext_wall": "External Wall",
        "prod_chute": "Refuse Chute",
        "prod_semi_slab": "Semi-precast Slab",
        "prod_conc_slab": "Concrete Slab",
        "proj_keitak": "Kai Tak",
        "proj_cullinan_harbour": "Cullinan Harbour",
        "proj_tinshuiwai": "Tin Shui Wai",
        "proj_yoho_west": "Yoho West",
        "proj_saisha": "Sai Sha",
        "proj_sierra_sea": "Sierra Sea",
        "proj_cullinan_sky": "Cullinan Sky",
        "proj_tuenmun": "Tuen Mun",
        "proj_novoland": "NOVOLAND",
        "proj_tsuenwan": "Tsuen Wan",
        "proj_1_sha_tsui_rd": "1 Sha Tsui Road",
        "proj_pakshekkok": "Pak Shek Kok",
        "proj_university_hill": "University Hill",
        "proj_yuenlong": "Yuen Long",
        "proj_yoho_hub_2": "The YOHO Hub Phase 2",
        "proj_shatin": "Shatin",
        "proj_shatin_name": "St Michel",
        "proj_taikoktsui": "Tai Kok Tsui",
        "proj_taikoktsui_name": "Le Moment",
        "proj_tsingyi": "Tsing Yi",
        "proj_tsingyi_name": "The Grand Marine",
        "proj_southisland": "Island South",
        "proj_southisland_name": "La Marina",
        "proj_saiyingpun": "Sai Ying Pun",
        "proj_saiyingpun_name": "15 Western Street",
        "related_business_title": "Related Business",
        "related_concrete_title": "Concrete",
        "related_concrete_desc": "Our sister company - Glorious Concrete (H.K.) Ltd., specializes in the production and supply of high-quality concrete and precast components. With comprehensive production facilities and strict quality control, Glorious Concrete provides stable and reliable building material support for close partners. Through collaboration between departments, we ensure construction progress and cost-effectiveness, while promoting the application of innovative technologies to build a solid foundation for various construction projects.",
        "website_label": "Website",
        "qualifications_title": "Professional Qualifications",
        "qualifications_placeholder": "Content for professional qualifications will be added here.",
        "business_title": "Our Business",
        "eng_projects": "Engineering Projects",
        "cat_residential": "Residential Buildings",
        "cat_infrastructure": "Infrastructure",
        "cat_domestic": "Domestic/Macau",
        "tbl_project_name": "Project Name",
        "tbl_product": "Precast Concrete Product",
        "tbl_developer": "Developer",
        "tbl_period": "Construction Period",
        "sus_title": "Sustainability",
        "env_commitment_title": "Environmental Commitment",
        "env_commitment_desc": "We recognize that urban development must go hand in hand with environmental protection. OPL continuously drives innovation and improvement to minimize the environmental impact of construction, safeguarding a sustainable ecology for society and future generations.",
        "qm_cert_title": "Quality Management & Certification",
        "qm_cert_desc_1": "We ensure the quality of every precast component through rigorous processes. From raw material inspection and factory production to on-site installation, we adhere to international and local standards with multiple inspection checkpoints. Through intelligent equipment and precise monitoring, we ensure dimensional accuracy and stable performance, providing reliable, safe, and sustainable building solutions for our partners.",
        "qm_cert_desc_2": "OPL has been awarded ISO9001 and ISO14001 certifications by the HKQAA for design, production, quality, and environmental protection, fully affirming our professional standards. Meanwhile, our Dongguan factory's Occupational Health and Safety Management has been assessed and certified by the Elvey Quality Certification Center, further demonstrating our commitment to safety and responsibility.",
        "env_protect_title": "Environmental Protection",
        "env_protect_desc": "OPL is committed to implementing environmental protection and sustainability practices in all business operations.",
        "qm_title": "Quality Management",
        "qm_policy_title": "Quality Policy",
        "qm_policy_desc": "It is the objective of Orientfunds Precast Limited to operate in accordance with the requirements of ISO9001, to produce and supply precast concrete products to the satisfaction of customers.",
        "qm_control_title": "Quality Control",
        "qm_control_desc": "Comprehensive Quality Inspection System: Incoming Material Inspection, In-process Inspection, Finished Product Inspection.",
        "tbl_level_1": "Level 1",
        "tbl_level_2": "Level 2",
        "tbl_level_3": "Level 3",
        "cert_title": "Quality Certification",
        "cert_desc": "ISO9001 & 14001 Certificates are accredited to OPL by HKQAA. OPL is one of the QSPSC certified precast concrete producers.",
        "careers_title": "Careers",
        "join_us_title": "Join Us",
        "join_us_desc": "At Orientfunds, we value talent development and provide excellent working environment and professional growth opportunities.",
        "job_eng_title": "Engineering Positions",
        "job_eng_desc": "Looking for experienced engineers to join our team.",
        "job_qc_title": "Quality Control",
        "job_qc_desc": "Responsible for product quality inspection and control.",
        "job_pm_title": "Project Management",
        "job_pm_desc": "Manage large-scale construction projects and coordinate team resources.",
        "job_opp_title": "Job Opportunities",
        "job_opp_desc_1": "We invite aspiring individuals to join our team and explore the future together. We value talent and provide comprehensive training, benefits, and competitive remuneration packages. To apply, please click \"<a href='#' style='color:#4CAF50; text-decoration:underline;'>Apply Here</a>\" and complete the online application form.",
        "job_opp_desc_2": "All job applications will be treated in strict confidence by authorized personnel and used for recruitment purposes only. Applicants not contacted within three months after the deadline may consider their applications unsuccessful. We will safely destroy the data of all unsuccessful applicants after six months. In case of any discrepancy between the English and Chinese versions, the English version shall prevail.",
        "interested_title": "Interested in joining us?",
        "interested_desc": "Please contact us to learn more about job opportunities.",
        "contact_title": "Contact Us",
        "general_inquiry": "General Inquiry",
        "head_office": "Head Office",
        "domestic_address": "Domestic Address",
        "contact_page_title": "Contact Us",
        "contact_hq": "Head Office",
        "contact_factory": "Dongguan Factory",
        "contact_hq_full": "Orientfunds Precast Limited (Head Office)",
        "contact_factory_full": "Dongguan Orientfunds Construction Materials Products Co., Ltd. (Dongguan Factory)", 
        "contact_hq_address": "Address: Units Nos. 2201-2211 and 2220-2225, Level 22, Tower 1, Metroplaza, 223 Hing Fong Road, Kwai Fong, N.T.",
        "contact_hq_tel": "Tel: (852) 2559 5765",
        "contact_hq_fax": "Fax: (852) 2517 0873",
        "contact_hq_email": "Email: opl-enquiry@orientfunds.com.hk",
        "contact_factory_address": "Address: No.3 Lianjian Road, Shatian Town, Dongguan, Guangdong, China Postal Code: 523990",
        "contact_factory_tel": "Tel: (86) 769 8886 8880",
        "contact_factory_fax": "Fax: (86) 769 8886 8820",
        "contact_gcl_title": "Glorious Concrete (H.K.) Limited",
        "contact_gcl_address": "Address: Flat 2201, 22/F, Tower 1, Metroplaza, No. 223 Hing Fong Road, Kwai Fong, Hong Kong",
        "contact_gcl_tel": "Tel: (852) 2546 2038",
        "contact_gcl_fax": "Fax: (852) 2517 0873",
        "contact_gcl_email": "Email: gcl-enquiry@glorious.com.hk",
        "contact_tw_title": "Tsuen Wan Plant",
        "contact_tw_address": "Plant Address: 13-17 Fu Uk Road, Kwai Chung, NT KCTL 169",
        "contact_yy_title": "Yick Yuen Plant",
        "contact_yy_address": "Plant Address: Lot 1824 in DD 130, Yick Yuen Village, Tuen Mun, NT",
        "contact_kt_title": "Kam Tin Plant",
        "contact_kt_address": "Plant Address: Lot 700 in DD 114, Lam Kam Road, Kam Tin, Shek Kong, NT",
        "contact_tm_title": "Tam Mei Warehouse",
        "contact_tm_address": "Plant Address: Maintenance Depot at Tam Mei Section, Castle Peak Road, Yuen Long, NT DD107, Lot 1743 SC RP (Part)",
        "val_title": "Core Values",
        "val_goal_title": "Goal",
        "val_goal_desc": "To be the driving force of the city's construction and development.",
        "val_mission_title": "Mission",
        "val_combined_title": "Goal, Mission, Vision",
        "val_mission_desc": "To provide reliable building material solutions, supporting the city's vitality with precast components.",
        "val_vision_title": "Vision",
        "val_vision_desc": "To become the most influential green precast brand in Asia, leading the future of the industry.",
        "mile_title": "Milestones",
        "milestone_desc_1979": "Glorious Concrete founded, beginning operations in Hong Kong's concrete industry.",
        "milestone_desc_1980": "Established production facilities and expanded service capacity.",
        "milestone_desc_1990": "Became a leading supplier for major infrastructure and building projects.",
        "milestone_desc_2000": "Successfully transitioned to modern production techniques and quality standards.",
        "milestone_desc_2010": "Expanded operations and enhanced technical capabilities.",
        "milestone_desc_2020": "Adapted to market changes and increased product innovation initiatives.",
        "milestone_desc_2021": "Launched new product lines and expanded market presence.",
        "milestone_desc_2022": "Successfully developed and introduced Low-density Concrete Partition to the market.",
        "milestone_desc_2023": "Initiated R&D on Hybrid/Concrete MiC, branded as \"Ease Living House.\"",
        "milestone_desc_2024": "Secured patent for fully prefabricated Low-density Concrete Partition.",
        "milestone_desc_2025": "Continuing innovation and expansion of sustainable building solutions.",
        "milestone_desc_1998": "Company established, focusing on Housing Authority and Housing Society projects.",
        "milestone_desc_2002": "Expanded into private sector, undertaking major private construction projects.",
        "milestone_desc_2019": "Began R&D on MiC technology, launched the first Orientfunds Concrete MiC product.",
        "awards_title": "Awards & Recognition",
        "awards_desc": "Received multiple industry certifications and recognitions.",
        "sister_title": "Sister Companies",
        "sister_desc": "Glorious Concrete (HK) Limited and Orientfunds Precast Ltd. are sister companies headquartered in Hong Kong, specializing in the concrete business. Both companies uphold professionalism and innovation, dedicated to providing high-quality concrete products and solutions, with services covering construction, infrastructure, and diverse engineering projects. Leveraging Hong Kong's geographical advantages and a comprehensive logistics network, the enterprises efficiently meet customer needs and continuously expand their business footprint.",
        "website_label": "Website: ",
        "about_hongfai_title": "About Orientfunds",
        "about_hongfai_desc": "Since its establishment in 1998, Orientfunds has focused on high-quality manufacturing and cross-border services. The company established a modern factory in Shatian, Dongguan, built along the water. Its superior geographical location and natural proximity to waterways provide unique advantages for efficient transportation. The factory is only over 100 kilometers from Hong Kong, with a well-developed transportation network. Water transport to Hong Kong takes about 6 hours, and it takes only just over three hours by car via Huanggang, Liantang, or Shenzhen Bay ports. Leveraging this strategic location, Orientfunds can rapidly connect Guangdong and Hong Kong, providing efficient and reliable cross-border supply chain support for its partners.<br><br>Orientfunds possesses comprehensive production and logistics facilities, including a concrete plant, storage yards, sand and gravel warehouses, and ten all-weather production workshops. Even in adverse weather conditions, it can maintain high-efficiency operations, ensuring quality and progress. The factory area is equipped with movable canopies, electric concrete vehicles, and skid steer loaders to enhance production and finishing efficiency. The storage area covers 25,000 square meters and is currently used for storing precast facade elements. The company also has an independent pier capable of handling products weighing over 30 tons and accommodating large vessels. Combined with mature land transportation, this ensures unimpeded transport by both sea and land.",
        "cert_patent_title": "Qualifications and Patents",
        "biz_panel_mortar1": "Ready-Mixed Concrete Products",
        "biz_panel_mortar2": "Ready-Mixed Mortar/Floor Screed Products",
        "biz_panel_gypsum": "Pre-Packaged Gypsum-Based Products",
        "biz_mortar1_title": "Pre-mixed Concrete Products",
        "biz_mortar1_col1_title": "Product Names",
        "biz_mortar1_item1": "Normal concrete mix: (55 MPa and below)",
        "biz_mortar1_item2": "High-strength reinforced concrete: (60 MPa and above)",
        "biz_mortar1_col1_subtitle": "Fire-resistant Concrete",
        "biz_mortar1_item3": "Lightweight aggregate: (density below 1,350 kg/m³)",
        "biz_mortar1_item4": "Lightweight aggregate concrete: (12 MPa in 4 hours)",
        "biz_mortar1_col2_title": "Special Concrete",
        "biz_mortar1_item5": "Fiber concrete: (fiber content approx. 1650 kg/m³ - 1850 kg/m³) (Fire rating: HK30112893)",
        "biz_mortar1_item6": "Low-density reinforced concrete: (density 1850 kg/m³ with 4-hour fire resistance) (Fire rating: HK30127477)",
        "biz_mortar1_item7": "Low-density concrete: (density 100 MPa)",
        "biz_mortar2_title": "Pre-mixed Mortar Products",
        "biz_mortar2_col1_title": "Product Specifications",
        "biz_mortar2_item1": "Plastering mortar: suitable for interior and exterior wall plastering with good workability",
        "biz_mortar2_item2": "Masonry mortar: for brick/block masonry works",
        "biz_mortar2_item3": "Floor mortar: suitable for floor leveling and repair",
        "biz_mortar2_col2_title": "Product Features",
        "biz_mortar2_item4": "✓ Precise mix ratio with stable quality",
        "biz_mortar2_item5": "✓ Convenient application and labor saving",
        "biz_mortar2_item6": "✓ Eco-friendly with reduced dust",
        "biz_mortar2_item7": "✓ Reliable strength and strong durability",
        "biz_gypsum_title": "Pre-packaged Gypsum-based Products",
        "biz_gypsum_col1_title": "Product Series",
        "biz_gypsum_item1": "Gypsum plaster mortar: for indoor wall plastering",
        "biz_gypsum_item2": "Gypsum self-leveling: suitable for fast floor leveling",
        "biz_gypsum_item3": "Gypsum repair mortar: for wall repair and finishing",
        "biz_gypsum_col2_title": "Product Advantages",
        "biz_gypsum_item4": "✓ Fast application and shorter project duration",
        "biz_gypsum_item5": "✓ Smooth surface with less post-treatment",
        "biz_gypsum_item6": "✓ Environmentally safe for indoor use",
        "biz_gypsum_item7": "✓ Regulates humidity and improves environment",
        "biz_cert_block_title": "CIC Green Product Certification",
        "biz_cert_col_product": "Product Name",
        "biz_cert_col_grade": "Carbon Grade",
        "biz_grade_platinum": "Platinum",
        "biz_grade_gold": "Gold",
        "biz_grade_silver": "Silver",
        "biz_cert_item1": "C30 GGBS (Max binder content 450kg/m³)",
        "biz_cert_item2": "C30 GGBS (Max binder content 470kg/m³)",
        "biz_cert_item3": "C35 GGBS (Max binder content 470kg/m³)",
        "biz_cert_item4": "C35 Fly Ash (Max binder content 400kg/m³)",
        "biz_cert_item5": "C40 GGBS (Max binder content 480kg/m³)",
        "biz_cert_item6": "C40 Fly Ash (Max binder content 480kg/m³)",
        "biz_cert_item7": "C45 GGBS (Max binder content 500kg/m³)",
        "biz_cert_item8": "C45 GGBS (Max binder content 550kg/m³)",
        "biz_cert_item9": "C45 Fly Ash (Max binder content 500kg/m³)",
        "biz_cert_item10": "C50 Fly Ash (Max binder content 540kg/m³)",
        "biz_cert_item11": "C60 GGBS (Max binder content 550kg/m³)",
        "biz_cert_item12": "C60 Fly Ash (Max binder content 550kg/m³)",
        "biz_cert_item13": "C80 GGBS + Silica Fume (Max binder content 600kg/m³)",
        "biz_cert_item14": "C80 Fly Ash + Silica Fume (Max binder content 600kg/m³)",
        "biz_cert_item15": "C30 Fly Ash (Max binder content 420kg/m³)",
        "biz_cert_item16": "C45 Cement (Max binder content 420kg/m³)",
        "biz_cert_item17": "C60 Cement (Max binder content 470kg/m³)",
        "biz_cert_item18": "C30 Cement (Max binder content 450kg/m³)",
        "biz_cert_item19": "C35 Cement (Max binder content 420kg/m³)",
        "biz_cert_item20": "C40 Cement (Max binder content 450kg/m³)",
        "biz_cert_item21": "C45 Cement (Max binder content 470kg/m³)",
        "biz_patent_block_title": "Short-term Patent Certificates",
        "biz_patent_col_name": "Invention Name",
        "biz_patent_col_no": "Patent No.",
        "biz_patent_item1_name": "Low-density cement-based composite material for engineering use and its production method",
        "biz_patent_item1_no": "HK30127477",
        "biz_patent_item2_name": "Lightweight Concrete",
        "biz_patent_item2_no": "HK30112993",
        "iso_desc": "ISO Certification: Audited by third-party organizations to ensure the management system meets international standards.",
        "patent_desc": "Patents: Granted by the government to protect exclusive rights to technology or design.",
        "pqm_title": "Precast Quality Management",
        "pqm_desc": "We ensure the quality of every precast component through a rigorous process. From raw material inspection and factory production to on-site installation, we follow international and local standards with multiple testing stages. Through intelligent equipment and precise monitoring, we ensure accurate dimensions and stable performance, providing reliable, safe, and sustainable building solutions for our partners.",
        "iso14001_text": "ISO 14001:2015<br>Certificate No: CC 5665",
        "iso9001_text": "ISO 9001:2015<br>Certificate No: CC 1538",
        "three_inspection_title": "Three-Inspection System",
        "three_inspection_desc": "Orientfunds' Quality Control Department strictly monitors all products to ensure that only high-quality products are delivered to customers. The company fully implements the 'Three-Inspection System' — Self-inspection, Re-inspection, and Special Inspection — to ensure stable quality. The Production Department and Quality Team are responsible for self-inspection and re-inspection, while the Zhongshan Office is appointed by the head office to conduct weekly special inspections at the Dongguan factory, forming a multi-level quality control mechanism.",
        "insp_self": "Self-inspection (Production Dept)",
        "insp_re": "Re-inspection (Quality Team)",
        "insp_special": "Special Inspection (Zhongshan Office)",
        "traceability_title": "Batch-by-Batch Handover",
        "traceability_desc": "Orientfunds follows the 'Batch-by-Batch Handover' principle, using QR Codes to track the entire production process. From rebar tying, mold installation, and concreting to rectification and final inspection, every step is recorded to ensure quality and progress. If any product issues arise, the system can trace back to the relevant workers and inspectors for follow-up."
    },
    "zh": {
        "nav_home": "首頁",
        "nav_about": "關於我們",
        "breadcrumb_home": "主頁",
        "nav_business": "公司業務",
        "nav_sustainability": "可持續發展",
        "nav_news": "最新動態",
        "nav_careers": "事業發展",
        "nav_contact": "聯絡我們",
        "completed_projects": "已完成工程項目",
        "btn_switch_en": "EN",
        "btn_switch_zh": "繁",
        "btn_switch_cn": "简",
        "footer_intro": "鴻輝預製件有限公司成立於1998年，專門從事預製混凝土構件的生產和供應。",
        "footer_quick_links": "快速連結",
        "footer_contact_title": "聯絡我們",
        "footer_headquarters": "總公司：",
        "footer_factory": "東莞廠房：",
        "footer_copyright": "Copyright © 2026 永輝混凝土( 香港) 有限公司 ，版權所有。",
        "hero_title": "克服困難，開拓新路",
        "index_about_title": "關於永輝",
        "index_about_desc": "永輝混凝土（香港）有限公司為新鴻基地產全資附屬公司，成立於 1979 年，專注提供優質混凝土及工程服務。多年來為地基、土木、樓宇及基礎設施項目提供穩定可靠的供應，並以「以心建家」為承諾，持續追求卓越品質，打造安全耐用的建築基礎。",
        "btn_learn_more": "了解更多 →",
        "section_projects": "工程項目",
        "section_strength": "公司實力",
        "strength_title": "我們具備完整的專業能力，<br>能夠實現他人認為不可能的工程。",
        "index_strength_desc_1": "當其他人追逐潮流之際，我們專注於重新定義建築的可能性。從地基工程、混凝土配方到環保材料與施工技術，我們皆具備深厚專業能力。真正令我們與眾不同的，是我們不只停留在水泥與鋼筋，而是以工程師的思維突破界限。",
        "index_strength_desc_2": "在綠色建築與智慧城市的時代，我們不僅適應，更主動塑造未來。結合建築專業與環保創新，融合創意解難與高效執行，從工地到社區，我們交付能經得起時間考驗的混凝土方案。",
        "stat_years": "年專業經驗",
        "stat_projects": "成功項目",
        "serve_clients": "服務客戶",
        "production_volume": "生產量(立方米)",
        "serve_customer": "客戶滿意度",
        "cta_title": "公司實力",
        "cta_desc": "了解更多關於我們的服務和項目",
        "btn_contact_us": "聯絡我們",
        "about_title": "關於我們",
        "about_intro_title": "公司簡介",
        "about_profile_title": "公司概況",
        "about_profile_desc": "鴻輝預製件有限公司成立於1998年。我們的工廠位於東莞市沙田鎮。我們是一家全資企業，投資超過8000萬港元，佔地面積超過80,000平方米，擁有天然水道，水路運輸便利。",
        "about_location_title": "廠房位置",
        "about_location_desc": "東莞廠房距離香港100公里，交通網絡完善。廠房位於珠江獅子洋入口處。海路前往香港僅需6小時。經陸路從皇崗或文錦渡前往香港需時2小時。",
        "core_values": "核心價值",
        "facilities": "設施",
        "zone_one_title": "第一工區 - 主力生產樓宇預製件",
        "zone_one_desc": "第一工區由5個有蓋車間、堆場和混凝土攪拌站組成。5個有蓋車間確保在各種天氣條件下的高質量和準時生產。我們有能力同時生產相當於25座樓宇的預製產品，即處理最少100套模具，日產量超过700噸。",
        "zone_two_title": "第二工區 - 大型構件生產",
        "zone_two_desc": "第二工區鑄造場和堆場佔地25,000平方米。配備2台龍門吊機（各80噸和50噸）。主要用於生產重型預製構件，如管片、大型預製樑/柱和外牆、隔音屏障板等。",
        "jetty_title": "碼頭",
        "jetty_desc": "我們的碼頭可停靠超過10,000噸的駁船。配有2套固定吊機（150噸和80噸），方便裝載大型預製構件。",
        "tech_advantage_title": "技術優勢",
        "tech_advantage_desc": "定期與知名機構（如香港大學、理工大學）及組織舉辦預製件研討會。",
        "business_products_title": "產品",
        "prod_mic": "MiC組裝合成建築法",
        "prod_wall_panel": "輕質混凝土間牆板",
        "prod_facade": "佛沙",
		"prod_steel_mic": "鋼結構組裝合成建築法",
        "prod_conc_mic": "全混凝土組裝合成建築法",
        "prod_stair": "樓梯",
        "prod_balcony": "露台",
        "prod_ext_wall": "外牆",
        "prod_chute": "垃圾槽",
        "prod_semi_slab": "半樓板",
        "prod_conc_slab": "混凝土板",
        "proj_keitak": "啟德",
        "proj_cullinan_harbour": "天璽 • 海",
        "proj_tinshuiwai": "天水圍",
        "proj_yoho_west": "Yoho West",
        "proj_saisha": "西沙",
        "proj_sierra_sea": "Sierra Sea",
        "proj_cullinan_sky": "天璽 • 天",
        "proj_tuenmun": "屯門",
        "proj_novoland": "NOVOLAND",
        "proj_tsuenwan": "荃灣",
        "proj_1_sha_tsui_rd": "沙咀道1號",
        "proj_pakshekkok": "白石角",
        "proj_university_hill": "University Hill",
        "proj_yuenlong": "元朗",
        "proj_yoho_hub_2": "The YOHO Hub 2期",
        "proj_shatin": "沙田",
        "proj_shatin_name": "瓏珀山",
        "proj_taikoktsui": "大角咀",
        "proj_taikoktsui_name": "傲寓",
        "proj_tsingyi": "青衣",
        "proj_tsingyi_name": "明翹匯",
        "proj_southisland": "港島南",
        "proj_southisland_name": "揚海",
        "proj_saiyingpun": "西營盤",
        "proj_saiyingpun_name": "西邊街15號",
        "related_business_title": "相關業務",
        "related_concrete_title": "混凝土",
        "related_concrete_desc": "我們的姊妹公司 - 永輝混凝土(香港)有限公司，專注於高品質混凝土及預製組件的生產與供應。憑藉完善的生產設施與嚴格的品質監控，永輝混凝土為緊密的合作夥伴提供穩定、可靠的建材支持。透過各部門協作，我們確保施工進度與成本效益，同時推動創新技術的應用，為各類建築項目打造堅實基礎。",
        "website_label": "網站",
        "qualifications_title": "專業資格",
        "qualifications_placeholder": "專業資格內容將在此處添加。",
        "business_title": "公司業務",
        "eng_projects": "工程項目",
        "cat_residential": "住宅樓宇",
        "cat_infrastructure": "基建",
        "cat_domestic": "國內澳門",
        "tbl_project_name": "項目名稱",
        "tbl_product": "預製混凝土產品",
        "tbl_developer": "發展商",
        "tbl_period": "施工期",
        "sus_title": "可持續發展",
        "env_commitment_title": "環境承諾",
        "env_commitment_desc": "我們深知城市發展必須兼顧環境保護，港興持續推動創新與改進，減少建築對自然的影響，為社會與未來世代守護可持續的生態。",
        "qm_cert_title": "質量管理及品質認證",
        "qm_cert_desc_1": "我們以嚴謹的流程確保每一件預製構件的品質，從原材料檢驗、工廠生產到現場安裝，均遵循國際及本地標準，並設有多重檢測環節。透過智能化設備與精細化監控，我們確保產品尺寸精準、性能穩定，為合作夥伴提供可靠、安全、可持續的建築解決方案。",
        "qm_cert_desc_2": "OPL在設計、生產、品質及環保方面，已獲香港品質保證局頒發的 ISO9001 及 ISO14001 認證，充分肯定我們的專業水平。同時，東莞預製件廠的職業健康與安全管理亦獲得國家認可監督機構——埃爾維質量認證中心的評定及證書，進一步彰顯我們對安全與責任的承諾。",
        "env_protect_title": "環境保護",
        "env_protect_desc": "OPL 致力於在所有業務運營中實施環境保護和可持續發展實踐。",
        "qm_title": "質量管理",
        "qm_policy_title": "質量方針",
        "qm_policy_desc": "鴻輝預製件有限公司的目標是按照 ISO9001 國際標準的要求運作，生產並供應令客戶滿意的預製混凝土產品。",
        "qm_control_title": "質量控制",
        "qm_control_desc": "全面的質量檢驗系統：進料檢驗、過程檢驗、成品檢驗。",
        "tbl_level_1": "第一級",
        "tbl_level_2": "第二級",
        "tbl_level_3": "第三級",
        "cert_title": "質量認證",
        "cert_desc": "ISO9001 和 14001 證書由 HKQAA 頒發給 OPL。OPL 是 QSPSC 認證的預製混凝土生產商之一。",
        "careers_title": "事業發展",
        "join_us_title": "加入我們",
        "join_us_desc": "在鴻輝，我們重視人才發展，提供優良的工作環境和專業成長機會。",
        "job_eng_title": "工程職位",
        "job_eng_desc": "尋找經驗豐富的工程師加入我們的團隊。",
        "job_qc_title": "質量控制",
        "job_qc_desc": "負責產品質量檢驗和控制。",
        "job_pm_title": "項目管理",
        "job_pm_desc": "管理大型建設項目，協調團隊資源。",
        "job_opp_title": "職業機會",
        "job_opp_desc_1": "我們誠邀有志之士加入團隊，共同開拓未來。本公司重視人才，並提供完善的培訓、福利及具競爭力的薪酬待遇。如欲申請，請點擊「<a href='#' style='color:#4CAF50; text-decoration:underline;'>按此申請</a>」並完成線上職位申請表。",
        "job_opp_desc_2": "所有求職申請將由本公司授權人員以嚴格保密方式處理，並僅限於招聘用途。若申請人於截止日期後三個月內未收到通知，則可視為未獲錄用。我們會在六個月後安全銷毀所有未獲聘用申請者的資料。若中英文版本之間有任何差異，均以英文版本為準。",
        "interested_title": "有興趣加入我們吗？",
        "interested_desc": "請聯繫我們以了解更多工作機會。",
        "contact_title": "聯絡我們",
        "general_inquiry": "一般查詢",
        "head_office": "總辦事處",
        "domestic_address": "國內地址",
        "contact_page_title": "聯絡我們",
        "contact_hq": "總公司",
        "contact_factory": "東莞廠",
        "contact_hq_full": "鴻輝預製件有限公司 (總公司)",
        "contact_factory_full": "東莞鴻輝建築材料製品有限公司 (東莞廠)",
        "contact_hq_address": "地址: 香港葵芳興芳路223號新都會廣場第1座22樓2201室",
        "contact_hq_tel": "電話: (852) 2559 5765",
        "contact_hq_fax": "傳真: (852) 2517 0873",
        "contact_hq_email": "電郵: opl-enquiry@orientfunds.com.hk",
        "contact_factory_address": "國內廠址: 廣東省東莞市沙田鎮聯檢路3號 郵編 523990",
        "contact_factory_tel": "電話: (86) 769 8886 8880",
        "contact_factory_fax": "傳真: (86) 769 8886 8820",
        "contact_gcl_title": "永輝混凝土(香港)有限公司",
        "contact_gcl_address": "地址: 香港葵芳興芳路223號新都會廣場第1座22樓2201室",
        "contact_gcl_tel": "電話: (852) 2546 2038",
        "contact_gcl_fax": "傳真: (852) 2517 0873",
        "contact_gcl_email": "電郵: gcl-enquiry@glorious.com.hk",
        "contact_tw_title": "荃灣廠",
        "contact_tw_address": "廠址: 新界葵涌傅屋道 13-17 號 KCTL 169",
        "contact_yy_title": "亦園廠",
        "contact_yy_address": "廠址: 新界屯門奕園村 130 約 1824 地段",
        "contact_kt_title": "錦田廠",
        "contact_kt_address": "廠址: 新界石崗錦田林錦公路第114約第700地段",
        "contact_tm_title": "潭尾倉",
        "contact_tm_address": "廠址: 新界元朗青山公路潭尾段維修工場DD107, Lot 1743 SC RP (Part)",
        "val_title": "核心價值",
        "val_goal_title": "目標",
        "val_goal_desc": "成為城市建設最堅實的推動力，每一件預製構件都是承載夢想的基石，透過品質、創新與責任，讓橋樑、高樓與道路更穩固、更美好。",
        "val_mission_title": "使命",
        "val_combined_title": "目標、使命、願景",
        "val_mission_desc": "以建築預製件承托城市生命力，我們承諾為合作伙伴提供可靠、準時、具競爭力的支持，為社會打造安全、環保、可持續的建材，為未來世代留下可信的基礎。",
        "val_vision_title": "願景",
        "val_vision_desc": "成為亞洲最具影響力的綠色預製件品牌，推動城市邁向低碳未來，透過智能生產與智慧物流，打造「未來工廠」，讓科技與環保並肩前行，承載世代的夢想與希望。",
        "mile_title": "里程碑",
        "milestone_desc_1979": "永輝混凝土成立，開始在香港混凝土行業運營。",
        "milestone_desc_1980": "建立生產設施並擴大服務容量。",
        "milestone_desc_1990": "成為大型基礎設施和建築項目的領先供應商。",
        "milestone_desc_2000": "成功過渡到現代化生產技術和品質標準。",
        "milestone_desc_2010": "擴展營運並增強技術能力。",
        "milestone_desc_2020": "適應市場變化並增加產品創新舉措。",
        "milestone_desc_2021": "推出新產品線並擴大市場占有率。",
        "milestone_desc_2022": "成功研發並推出輕石矢間牆板，正式進入市場。",
        "milestone_desc_2023": "開始研發鋼/石矢 MiC，並命名為「簡悅屋」。",
        "milestone_desc_2024": "全預製輕質混凝土牆板獲得專利認證。",
        "milestone_desc_2025": "持續創新並擴展可持續建築解決方案。",
        "milestone_desc_1998": "公司成立，專注承接房署及房協工程。",
        "milestone_desc_2002": "業務拓展至私人工程，開始承接大型私人項目。",
        "milestone_desc_2019": "投入研發 MiC 技術，推出首個鴻輝石矢 MiC 產品。",
        "milestone_desc_2024": "全預製輕質混凝土牆板獲得專利認證。",
        "awards_title": "獎項及嘉許",
        "awards_desc": "榮獲多項產業認証和嘉許",
        "about_hongfai_title": "關於鴻輝",
        "about_yongfai_title": "關於永輝",
        "website_label": "網頁: ",
        "sister_title": "姊妹公司",
        "sister_desc": "永輝混凝土(香港)有限公司與鴻輝預製件有限公司同屬姊妹企業，總部設於香港，專注於混凝土業務。兩家公司秉承專業精神與創新理念，致力提供高品質的混凝土產品及解決方案，服務涵蓋建築、基建及多元工程項目。憑藉香港的地理優勢與完善的物流網絡，企業能高效滿足客戶需求，並持續拓展業務版圖。",
        "about_hongfai_desc": "鴻輝自1998年成立以來，專注高品質製造與跨境服務。公司於東莞沙田設立現代化廠房，依水而建，地理位置優越，天然臨近水路，為高效運輸提供獨特優勢。廠房距離香港僅一百多公里，交通網絡四通八達。水路運輸至港約需6小時，經皇崗、蓮塘或深圳灣口岸車程亦僅三個多小時。憑藉此戰略區位，鴻輝能迅速連接粵港兩地，為合作夥伴提供高效可靠的跨境供應鏈支持。<br><br>鴻輝擁有完善的生產與物流設施，包括石矢廠、堆放場、沙石倉及十個全天候生產車間，即使在惡劣天氣下亦能保持高效運作，確保品質與進度。廠區設有活動雨棚、電動石矢車及滑移裝載機，提升生產與裝修效率。倉存區面積達 25,000 平方米，現用作預製件外牆貨存。公司更設有獨立碼頭，可處理三十噸以上產品並容納大型船舶，配合成熟的陸路運輸，實現海陸暢通無阻。",
        "about_yongfai_desc": "永輝混凝土（香港）有限公司為新鴻基地產的全資附屬公司，專注提供優質混凝土及相關工程服務。自1979年成立以來，永輝憑藉專業經驗與技術，在香港建造業中發揮重要作用，為地基、土木、樓宇及基礎設施項目提供穩定可靠的混凝土供應。公司深諳建築需求，能因應不同項目提供多元化解決方案。秉持「以心建家」的承諾，永輝以「克服困難，開拓新路」為信念，持續追求卓越品質，打造堅固耐用的建築基礎，營造安全舒適的居住環境。",
        "cert_patent_title": "資格認證及專利",
        "biz_panel_mortar1": "預拌混凝土產品",
        "biz_panel_mortar2": "預拌砂漿產品",
        "biz_panel_gypsum": "預包裝石膏基產品",
        "biz_mortar1_title": "預拌混凝土產品",
        "biz_mortar1_col1_title": "產品名稱",
        "biz_mortar1_item1": "普通混凝土混合物：(55 MPa及以下)",
        "biz_mortar1_item2": "高強度鋼筋混凝土：(60 MPa及以上)",
        "biz_mortar1_col1_subtitle": "防火混凝土",
        "biz_mortar1_item3": "輕骨料：(密度小於1,350 kg/m³)",
        "biz_mortar1_item4": "輕骨料混凝土：(4小時達12 MPa)",
        "biz_mortar1_col2_title": "特種混凝土",
        "biz_mortar1_item5": "纖維混凝土：(纖維含量約1650 kg/m³ - 1850 kg/m³) (耐火等級: HK30112893)",
        "biz_mortar1_item6": "低密度鋼筋混凝土：(密度為1850 kg/m³並具4小時耐火特性) (耐火等級: HK30127477)",
        "biz_mortar1_item7": "低密度混凝土：(密度為100 MPa)",
        "biz_mortar2_title": "預拌砂漿產品",
        "biz_mortar2_col1_title": "產品規格",
        "biz_mortar2_item1": "抹灰砂漿：適用於內外牆抹灰，具有良好的施工性能",
        "biz_mortar2_item2": "砌築砂漿：用於砌磚、砌塊等砌體工程",
        "biz_mortar2_item3": "地坪砂漿：適用於地面找平和修補",
        "biz_mortar2_col2_title": "產品特點",
        "biz_mortar2_item4": "✓ 配比精確，質量穩定",
        "biz_mortar2_item5": "✓ 施工便捷，節省人工",
        "biz_mortar2_item6": "✓ 綠色環保，減少粉塵",
        "biz_mortar2_item7": "✓ 強度可靠，耐久性強",
        "biz_gypsum_title": "預包裝石膏基產品",
        "biz_gypsum_col1_title": "產品系列",
        "biz_gypsum_item1": "石膏基抹灰砂漿：用於室內牆面抹灰",
        "biz_gypsum_item2": "石膏基自流平：適用於地面快速找平",
        "biz_gypsum_item3": "石膏基修補砂漿：用於牆面修補和修整",
        "biz_gypsum_col2_title": "產品優勢",
        "biz_gypsum_item4": "✓ 施工速度快，縮短工期",
        "biz_gypsum_item5": "✓ 表面光滑，減少後期處理",
        "biz_gypsum_item6": "✓ 環保無害，室內安全",
        "biz_gypsum_item7": "✓ 調節濕度，改善環境",
        "biz_cert_block_title": "建造業議會綠色產品認證",
        "biz_cert_col_product": "產品名稱",
        "biz_cert_col_grade": "碳等級",
        "biz_grade_platinum": "鉑金",
        "biz_grade_gold": "金",
        "biz_grade_silver": "銀",
        "biz_cert_item1": "C30礦渣微粉 (最高膠凝材料用量450kg/m³)",
        "biz_cert_item2": "C30礦渣微粉 (最高膠凝材料用量470kg/m³)",
        "biz_cert_item3": "C35礦渣微粉 (最高膠凝材料用量470kg/m³)",
        "biz_cert_item4": "C35粉煤灰 (最高膠凝材料用量400kg/m³)",
        "biz_cert_item5": "C40礦渣微粉 (最高膠凝材料用量480kg/m³)",
        "biz_cert_item6": "C40粉煤灰 (最高膠凝材料用量480kg/m³)",
        "biz_cert_item7": "C45礦渣微粉 (最高膠凝材料用量500kg/m³)",
        "biz_cert_item8": "C45礦渣微粉 (最高膠凝材料用量550kg/m³)",
        "biz_cert_item9": "C45粉煤灰 (最高膠凝材料用量500kg/m³)",
        "biz_cert_item10": "C50粉煤灰 (最高膠凝材料用量540kg/m³)",
        "biz_cert_item11": "C60礦渣微粉 (最高膠凝材料用量550kg/m³)",
        "biz_cert_item12": "C60粉煤灰 (最高膠凝材料用量550kg/m³)",
        "biz_cert_item13": "C80礦渣微粉+硅粉 (最高膠凝材料用量600kg/m³)",
        "biz_cert_item14": "C80粉煤灰+硅粉 (最高膠凝材料用量600kg/m³)",
        "biz_cert_item15": "C30粉煤灰 (最高膠凝材料用量420kg/m³)",
        "biz_cert_item16": "C45英泥 (最高膠凝材料用量420kg/m³)",
        "biz_cert_item17": "C60英泥 (最高膠凝材料用量470kg/m³)",
        "biz_cert_item18": "C30英泥 (最高膠凝材料用量450kg/m³)",
        "biz_cert_item19": "C35英泥 (最高膠凝材料用量420kg/m³)",
        "biz_cert_item20": "C40英泥 (最高膠凝材料用量450kg/m³)",
        "biz_cert_item21": "C45英泥 (最高膠凝材料用量470kg/m³)",
        "biz_patent_block_title": "批予短期專利證明書",
        "biz_patent_col_name": "發明名稱",
        "biz_patent_col_no": "專利編號",
        "biz_patent_item1_name": "低密度工程用水泥基複合材料及其生產方法",
        "biz_patent_item1_no": "HK30127477",
        "biz_patent_item2_name": "輕質混凝土",
        "biz_patent_item2_no": "HK30112993",
        "iso_desc": "ISO 認證：由第三方機構審核，確保管理體系符合國際標準。",
        "patent_desc": "專利：由政府授權，保障技術或設計的獨占使用權。",
        "pqm_title": "預製件質量管理",
        "pqm_desc": "我們以嚴謹的流程確保每一件預製構件的品質。從原材料檢驗、工廠生產到現場安裝，均遵循國際及本地標準，並設有多重檢測環節。透過智能化設備與精細化監控，我們確保產品尺寸準確、性能穩定，為合作夥伴提供可靠、安全、可持續的建築解決方案。",
        "iso14001_text": "ISO 14001:2015<br>證書編號：CC 5665",
        "iso9001_text": "ISO 9001:2015<br>證書編號：CC 1538",
        "three_inspection_title": "三檢制度",
        "three_inspection_desc": "鴻輝品檢部對所有產品進行嚴密監察，確保交付客戶的均為優質產品。公司全面推行「三檢制度」—— 自檢、複檢及專檢，以保障品質穩定。生產部與品質組負責自檢及複檢，而中山辦則由總公司委派，每週前往東莞廠進行專檢，形成多層次的品質把關機制。",
        "insp_self": "自檢 (生產部)",
        "insp_re": "複檢 (品質組)",
        "insp_special": "專檢 (中山辦)",
        "traceability_title": "一行交一行",
        "traceability_desc": "鴻輝以「一行交一行」為原則，透過 QR Code 全程追蹤生產流程。從鐵籠捆紮、模具安裝及澆注石矢，到修補工序及成品檢驗，每一步均有記錄，確保品質與進度。若成品日後出現問題，系統可追溯至相關生產工人及驗收人員，方便跟進。"
    },
    "cn": {
        "nav_home": "首页",
        "nav_about": "关于我们",
        "breadcrumb_home": "主页",
        "nav_business": "公司业务",
        "nav_sustainability": "可持续发展",
        "nav_news": "最新动态",
        "nav_careers": "事业发展",
        "nav_contact": "联络我们",
        "completed_projects": "已完成工程项目",
        "btn_switch_en": "EN",
        "btn_switch_zh": "繁",
        "btn_switch_cn": "简",
        "footer_intro": "鸿辉预制件有限公司成立于1998年，专门从事预制混凝土构件的生产和供应。",
        "footer_quick_links": "快速链接",
        "footer_contact_title": "联络我们",
        "footer_headquarters": "总公司：",
        "footer_factory": "东莞厂房：",
        "footer_copyright": "Copyright © 2026 永辉混凝土( 香港) 有限公司 ，版权所有。",
        "hero_title": "克服困难，开拓新路",
        "index_about_title": "关于永辉",
        "index_about_desc": "永辉混凝土（香港）有限公司为新鸿基地产全资附属公司，成立于 1979 年，专注提供优质混凝土及工程服务。多年来为地基、土木、楼宇及基础设施项目提供稳定可靠的供应，并以「以心建家」为承诺，持续追求卓越品质，打造安全耐用的建筑基础。",
        "btn_learn_more": "了解更多 →",
        "btn_more": "更多 →",
        "btn_more": "更多 →",
        "section_projects": "工程項目",
        "section_strength": "公司实力",
        "strength_title": "我们具备完整的专业能力，能够实现他人认为不可能的工程。",
        "index_strength_desc_1": "当其他人追逐潮流之际，我们专注于重新定义建筑的可能性。从地基工程、混凝土配方到环保材料与施工技术，我们皆具备深厚专业能力。真正令我们与众不同的，是我们不只停留在水泥与钢筋，而是以工程师的思维突破界限。",
        "index_strength_desc_2": "在绿色建筑与智慧城市的时代，我们不仅适应，更主动塑造未来。结合建筑专业与环保创新，融合创意解难与高效执行，从工地到社区，我们交付能经得起时间考验的混凝土方案。",
        "stat_years": "年专业经验",
        "stat_projects": "成功项目",
        "serve_clients": "服务客户",
        "production_volume": "生产量(立方米)",
        "serve_customer": "客户满意度",
        "cta_title": "公司实力",
        "cta_desc": "了解更多关于我们的服务和项目",
        "btn_contact_us": "联络我们",
        "about_title": "关于我们",
        "about_intro_title": "公司简介",
        "about_profile_title": "公司概况",
        "about_profile_desc": "鸿辉预制件有限公司成立于1998年。我们的工厂位于东莞市沙田镇。我们是一家全资企业，投资超过8000万港元，占地面积超过80,000平方米，拥有天然水道，水路运输便利。",
        "about_location_title": "厂房位置",
        "about_location_desc": "东莞厂房距离香港100公里，交通网络完善。厂房位于珠江狮子洋入口处。海路前往香港仅需6小时。经陆路从皇岗或文锦渡前往香港需时2小时。",
        "core_values": "核心价值",
        "facilities": "设施",
        "zone_one_title": "第一工区 - 主力生产楼宇预制件",
        "zone_one_desc": "第一工区由5个有盖车间、堆场和混凝土搅拌站组成。5个有盖车间确保在各种天气条件下的高质量和准时生产。我们有能力同时生产相当于25座楼宇的预制产品，即处理最少100套模具，日产量超过700吨。",
        "zone_two_title": "第二工区 - 大型构件生产",
        "zone_two_desc": "第二工区铸造场和堆场占地25,000平方米。配备2台龙门吊机（各80吨和50吨）。主要用于生产重型预制构件，如管片、大型预制梁/柱和外墙、隔音屏障板等。",
        "jetty_title": "码头",
        "jetty_desc": "我们的码头可停靠超过10,000吨的驳船。配有2套固定吊机（150吨和80吨），方便装载大型预制构件。",
        "tech_advantage_title": "技术优势",
        "tech_advantage_desc": "定期与知名机构（如香港大学、理工大学）及组织举办预制件研讨会。",
        "business_products_title": "产品",
        "prod_mic": "MiC组装合成建筑法",
        "prod_wall_panel": "轻质混凝土间墙板",
        "prod_facade": "佛沙",
		"prod_steel_mic": "钢结构组装合成建筑法",
        "prod_conc_mic": "全混凝土组装合成建筑法",
        "prod_stair": "楼梯",
        "prod_balcony": "露台",
        "prod_ext_wall": "外墙",
        "prod_chute": "垃圾槽",
        "prod_semi_slab": "半楼板",
        "prod_conc_slab": "混凝土板",
        "proj_keitak": "启德",
        "proj_cullinan_harbour": "天玺 • 海",
        "proj_tinshuiwai": "天水围",
        "proj_yoho_west": "Yoho West",
        "proj_saisha": "西沙",
        "proj_sierra_sea": "Sierra Sea",
        "proj_cullinan_sky": "天玺 • 天",
        "proj_tuenmun": "屯门",
        "proj_novoland": "NOVOLAND",
        "proj_tsuenwan": "荃湾",
        "proj_1_sha_tsui_rd": "沙咀道1号",
        "proj_pakshekkok": "白石角",
        "proj_university_hill": "University Hill",
        "proj_yuenlong": "元朗",
        "proj_yoho_hub_2": "The YOHO Hub 2期",
        "proj_shatin": "沙田",
        "proj_shatin_name": "珑珀山",
        "proj_taikoktsui": "大角咀",
        "proj_taikoktsui_name": "傲寓",
        "proj_tsingyi": "青衣",
        "proj_tsingyi_name": "明翘汇",
        "proj_southisland": "港岛南",
        "proj_southisland_name": "扬海",
        "proj_saiyingpun": "西营盘",
        "proj_saiyingpun_name": "西边街15號",
        "related_business_title": "相关业务",
        "related_concrete_title": "混凝土",
        "related_concrete_desc": "我们的姊妹公司 - 永辉混凝土(香港)有限公司，专注于高品质混凝土及预制组件的生产与供应。凭借完善的生产设施与严格的品质监控，永辉混凝土为紧密的合作伙伴提供稳定、可靠的建材支持。透过各部门协作，我们确保施工进度与成本效益，同时推动创新技术的应用，为各类建筑项目打造坚实基础。",
        "website_label": "网站",
        "qualifications_title": "专业资格",
        "qualifications_placeholder": "专业资格内容将在此处添加。",
        "business_title": "公司业务",
        "eng_projects": "工程项目",
        "cat_residential": "住宅楼宇",
        "cat_infrastructure": "基建",
        "cat_domestic": "国内澳门",
        "tbl_project_name": "项目名称",
        "tbl_product": "预制混凝土产品",
        "tbl_developer": "发展商",
        "tbl_period": "施工期",
        "sus_title": "可持续发展",
        "env_commitment_title": "环境承诺",
        "env_commitment_desc": "我们深知城市发展必须兼顾环境保护，港兴持续推动创新与改进，减少建筑对自然的影响，为社会与未来世代守护可持续的生态。",
        "qm_cert_title": "质量管理及品质认证",
        "qm_cert_desc_1": "我们以严谨的流程确保每一件预制构件的品质，从原材料检验、工厂生产到现场安装，均遵循国际及本地标准，并设有多重检测环节。透过智能化设备与精细化监控，我们确保产品尺寸精准、性能稳定，为合作伙伴提供可靠、安全、可持续的建筑解决方案。",
        "qm_cert_desc_2": "OPL在设计、生产、品质及环保方面，已获香港品质保证局颁发的 ISO9001 及 ISO14001 认证，充分肯定我们的专业水平。同时，东莞预制件厂的职业健康与安全管理亦获得国家认可监督机构——埃尔维质量认证中心的评定及证书，进一步彰显我们对安全与责任的承诺。",
        "env_protect_title": "环境保护",
        "env_protect_desc": "OPL 致力于在所有业务运营中实施环境保护和可持续发展实践。",
        "qm_title": "质量管理",
        "qm_policy_title": "质量方针",
        "qm_policy_desc": "鸿辉预制件有限公司的目标是按照 ISO9001 国际标准的要求运作，生产并供应令客户满意的预制混凝土产品。",
        "qm_control_title": "质量控制",
        "qm_control_desc": "全面的质量检验系统：进料检验、过程检验、成品检验。",
        "tbl_level_1": "第一级",
        "tbl_level_2": "第二级",
        "tbl_level_3": "第三级",
        "cert_title": "质量认证",
        "cert_desc": "ISO9001 和 14001 证书由 HKQAA 颁发给 OPL。OPL 是 QSPSC 认证的预制混凝土生产商之一。",
        "careers_title": "事业发展",
        "join_us_title": "加入我们",
        "join_us_desc": "在鸿辉，我们重视人才发展，提供优良的工作环境和专业成长机会。",
        "job_eng_title": "工程职位",
        "job_eng_desc": "寻找经验丰富的工程师加入我们的团队。",
        "job_qc_title": "质量控制",
        "job_qc_desc": "负责产品质量检验和控制。",
        "job_pm_title": "项目管理",
        "job_pm_desc": "管理大型建设项目，协调团队资源。",
        "job_opp_title": "职业机会",
        "job_opp_desc_1": "我们诚邀有志之士加入团队，共同开拓未来。本公司重视人才，并提供完善的培训、福利及具竞争力的薪酬待遇。如欲申请，请点击「<a href='#' style='color:#4CAF50; text-decoration:underline;'>按此申请</a>」并完成线上职位申请表。",
        "job_opp_desc_2": "所有求职申请将由本公司授权人员以严格保密方式处理，并仅限于招聘用途。若申请人于截止日期后三个月内未收到通知，则可视为未获录用。我们会在六个月后安全销毁所有未获聘用申请者的资料。若中英文版本之间有任何差异，均以英文版本为准。",
        "interested_title": "有兴趣加入我们吗？",
        "interested_desc": "请联系我们以了解更多工作机会。",
        "contact_title": "联络我们",
        "general_inquiry": "一般查询",
        "head_office": "总办事处",
        "domestic_address": "国内地址",
        "contact_page_title": "联络我们",
        "contact_hq": "总公司",
        "contact_factory": "东莞厂",        "contact_hq_full": "鸿辉预制件有限公司 (总公司)",
        "contact_factory_full": "东莞鸿辉建筑材料制品有限公司 (东莞厂)",        "contact_hq_address": "地址: 香港葵芳兴芳路223号新都会广场第1座22楼2201室",
        "contact_hq_tel": "电话: (852) 2559 5765",
        "contact_hq_fax": "传真: (852) 2517 0873",
        "contact_hq_email": "电邮: opl-enquiry@orientfunds.com.hk",
        "contact_factory_address": "国内厂址: 广东省东莞市沙田镇联检路3号 邮编 523990",
        "contact_factory_tel": "电话: (769) 8886 8880",
        "contact_factory_fax": "传真: (769) 8886 8820",
        "contact_gcl_title": "永辉混凝土(香港)有限公司",
        "contact_gcl_address": "地址: 香港葵芳兴芳路223号新都会广场第1座22楼2201室",
        "contact_gcl_tel": "电话: (852) 2546 2038",
        "contact_gcl_fax": "传真: (852) 2517 0873",
        "contact_gcl_email": "电邮: gcl-enquiry@glorious.com.hk",
        "contact_tw_title": "荃湾厂",
        "contact_tw_address": "厂址: 新界葵涌傅屋道 13-17 号 KCTL 169",
        "contact_yy_title": "亦园厂",
        "contact_yy_address": "厂址: 新界屯门奕园村 130 约 1824 地段",
        "contact_kt_title": "锦田厂",
        "contact_kt_address": "厂址: 新界石岗锦田林锦公路第114约第700地段",
        "contact_tm_title": "潭尾仓",
        "contact_tm_address": "厂址: 新界元朗青山公路潭尾段维修工场DD107, Lot 1743 SC RP (Part)",
        "val_title": "核心价值",
        "val_goal_title": "目标",
        "val_goal_desc": "成为城市建设最坚实的推动力，每一件预制构件都是承载梦想的基石，透过品质、创新与责任，让桥梁、高楼与道路更稳固、更美好。",
        "val_mission_title": "使命",
        "val_combined_title": "目标、使命、愿景",
        "val_mission_desc": "以建筑预制件承托城市生命力，我们承诺为合作伙伴提供可靠、准时、具竞争力的支持，为社会打造安全、环保、可持续的建材，为未来世代留下可信的基础。",
        "val_vision_title": "愿景",
        "val_vision_desc": "成为亚洲最具影响力的绿色预制件品牌，推动城市迈向低碳未来，透过智能生产与智慧物流，打造「未来工厂」，让科技与环保并肩前行，承载世代的梦想与希望。",
        "mile_title": "里程碑",
        "mile_1998_label": "主力房署及房协工程",
        "mile_1998_sublabel": "公司成立，主力承接房署及房协工程。",
        "mile_2002_label": "主力私人工程",
        "mile_2002_sublabel": "开始承接私人工程。",
        "milestone_desc_1979": "永辉混凝土成立，开始在香港混凝土行业运营。",
        "milestone_desc_1980": "建立生产设施并扩大服务容量。",
        "milestone_desc_1990": "成为大型基础设施和建筑项目的领先供应商。",
        "milestone_desc_2000": "成功过渡到现代化生产技术和品质标准。",
        "milestone_desc_2010": "扩展营运并增强技术能力。",
        "milestone_desc_2020": "适应市场变化并增加产品创新举措。",
        "milestone_desc_2021": "推出新产品线并扩大市场占有率。",
        "milestone_desc_2022": "成功研发并推出轻石矢间墙板，正式进入市场。",
        "milestone_desc_2023": "开始研发钢/石矢 MiC，并命名为「简悦屋」。",
        "milestone_desc_2024": "全预制轻质混凝土墙板获得专利认证。",
        "milestone_desc_2025": "持续创新并扩展可持续建筑解决方案。",
        "milestone_desc_1998": "公司成立，专注承接房署及房协工程。",
        "milestone_desc_2002": "业务拓展至私人工程，开始承接大型私人项目。",
        "milestone_desc_2019": "开始研发 MiC 技术，推出首个鸿辉石矢 MiC 产品。",
        "awards_title": "奖项及嘉许",
        "awards_desc": "荣获多项产业认证和嘉许",
        "about_hongfai_title": "关于鸿辉",
        "about_yongfai_title": "关于永辉",
        "website_label": "网页: ",
        "sister_title": "姐妹公司",
        "sister_desc": "永辉混凝土(香港)有限公司与鸿辉预制件有限公司同属姐妹企业，总部设于香港，专注于混凝土业务。两家公司秉承专业精神与创新理念，致力提供高品质的混凝土产品及解决方案，服务涵盖建筑、基建及多元工程项目。凭借香港的地理优势与完善的物流网络，企业能高效满足客户需求，并持续拓展业务版图。",
        "about_hongfai_desc": "鸿辉自1998年成立以来，专注高品质制造与跨境服务。公司于东莞沙田设立现代化厂房，依水而建，地理位置优越，天然临近水路，为高效运输提供独特优势。厂房距离香港仅一百多公里，交通网络四通八达。水路运输至港约需6小时，经皇岗、莲塘或深圳湾口岸车程亦仅三个多小时。凭借此战略区位，鸿辉能迅速连接粤港两地，为合作伙伴提供高效可靠的跨境供应链支持。<br><br>鸿辉拥有完善的生产与物流设施，包括混凝土厂、堆放场、沙石仓及十个全天候生产车间，即使在恶劣天气下亦能保持高效运作，确保品质与进度。厂区设有活动雨棚、电动混凝土车及滑移装载机，提升生产与装修效率。仓存区面积达25,000平方米，现用作预制件外墙货存。公司更设有独立码头，可处理三十吨以上产品并容纳大型船舶，配合成熟的陆路运输，实现海陆畅通无阻。",
        "about_yongfai_desc": "永辉混凝土（香港）有限公司为新鸿基地产的全资附属公司，专注提供优质混凝土及相关工程服务。自1979年成立以来，永辉凭借专业经验与技术，在香港建造业中发挥重要作用，为地基、土木、楼宇及基础设施项目提供稳定可靠的混凝土供应。公司深谙建筑需求，能因应不同项目提供多元化解决方案。秉持「以心建家」的承诺，永辉以「克服困难，开拓新路」为信念，持续追求卓越品质，打造坚固耐用的建筑基础，营造安全舒适的居住环境。",
        "cert_patent_title": "资格认证及专利",
        "biz_panel_mortar1": "预拌混凝土产品",
        "biz_panel_mortar2": "预拌砂浆产品",
        "biz_panel_gypsum": "预包装石膏基产品",
        "biz_mortar1_title": "预拌混凝土产品",
        "biz_mortar1_col1_title": "产品名称",
        "biz_mortar1_item1": "普通混凝土混合物：(55 MPa及以下)",
        "biz_mortar1_item2": "高强度钢筋混凝土：(60 MPa及以上)",
        "biz_mortar1_col1_subtitle": "防火混凝土",
        "biz_mortar1_item3": "轻骨料：(密度小于1,350 kg/m³)",
        "biz_mortar1_item4": "轻骨料混凝土：(4小时达12 MPa)",
        "biz_mortar1_col2_title": "特种混凝土",
        "biz_mortar1_item5": "纤维混凝土：(纤维含量约1650 kg/m³ - 1850 kg/m³) (耐火等级: HK30112893)",
        "biz_mortar1_item6": "低密度钢筋混凝土：(密度为1850 kg/m³并具4小时耐火特性) (耐火等级: HK30127477)",
        "biz_mortar1_item7": "低密度混凝土：(密度为100 MPa)",
        "biz_mortar2_title": "预拌砂浆产品",
        "biz_mortar2_col1_title": "产品规格",
        "biz_mortar2_item1": "抹灰砂浆：适用于内外墙抹灰，具有良好的施工性能",
        "biz_mortar2_item2": "砌筑砂浆：用于砌砖、砌块等砌体工程",
        "biz_mortar2_item3": "地坪砂浆：适用于地面找平和修补",
        "biz_mortar2_col2_title": "产品特点",
        "biz_mortar2_item4": "✓ 配比精确，质量稳定",
        "biz_mortar2_item5": "✓ 施工便捷，节省人工",
        "biz_mortar2_item6": "✓ 绿色环保，减少粉尘",
        "biz_mortar2_item7": "✓ 强度可靠，耐久性强",
        "biz_gypsum_title": "预包装石膏基产品",
        "biz_gypsum_col1_title": "产品系列",
        "biz_gypsum_item1": "石膏基抹灰砂浆：用于室内墙面抹灰",
        "biz_gypsum_item2": "石膏基自流平：适用于地面快速找平",
        "biz_gypsum_item3": "石膏基修补砂浆：用于墙面修补和修整",
        "biz_gypsum_col2_title": "产品优势",
        "biz_gypsum_item4": "✓ 施工速度快，缩短工期",
        "biz_gypsum_item5": "✓ 表面光滑，减少后期处理",
        "biz_gypsum_item6": "✓ 环保无害，室内安全",
        "biz_gypsum_item7": "✓ 调节湿度，改善环境",
        "biz_cert_block_title": "建造业议会绿色产品认证",
        "biz_cert_col_product": "产品名称",
        "biz_cert_col_grade": "碳等级",
        "biz_grade_platinum": "铂金",
        "biz_grade_gold": "金",
        "biz_grade_silver": "银",
        "biz_cert_item1": "C30矿渣微粉 (最高胶凝材料用量450kg/m³)",
        "biz_cert_item2": "C30矿渣微粉 (最高胶凝材料用量470kg/m³)",
        "biz_cert_item3": "C35矿渣微粉 (最高胶凝材料用量470kg/m³)",
        "biz_cert_item4": "C35粉煤灰 (最高胶凝材料用量400kg/m³)",
        "biz_cert_item5": "C40矿渣微粉 (最高胶凝材料用量480kg/m³)",
        "biz_cert_item6": "C40粉煤灰 (最高胶凝材料用量480kg/m³)",
        "biz_cert_item7": "C45矿渣微粉 (最高胶凝材料用量500kg/m³)",
        "biz_cert_item8": "C45矿渣微粉 (最高胶凝材料用量550kg/m³)",
        "biz_cert_item9": "C45粉煤灰 (最高胶凝材料用量500kg/m³)",
        "biz_cert_item10": "C50粉煤灰 (最高胶凝材料用量540kg/m³)",
        "biz_cert_item11": "C60矿渣微粉 (最高胶凝材料用量550kg/m³)",
        "biz_cert_item12": "C60粉煤灰 (最高胶凝材料用量550kg/m³)",
        "biz_cert_item13": "C80矿渣微粉+硅粉 (最高胶凝材料用量600kg/m³)",
        "biz_cert_item14": "C80粉煤灰+硅粉 (最高胶凝材料用量600kg/m³)",
        "biz_cert_item15": "C30粉煤灰 (最高胶凝材料用量420kg/m³)",
        "biz_cert_item16": "C45英泥 (最高胶凝材料用量420kg/m³)",
        "biz_cert_item17": "C60英泥 (最高胶凝材料用量470kg/m³)",
        "biz_cert_item18": "C30英泥 (最高胶凝材料用量450kg/m³)",
        "biz_cert_item19": "C35英泥 (最高胶凝材料用量420kg/m³)",
        "biz_cert_item20": "C40英泥 (最高胶凝材料用量450kg/m³)",
        "biz_cert_item21": "C45英泥 (最高胶凝材料用量470kg/m³)",
        "biz_patent_block_title": "批予短期专利证明书",
        "biz_patent_col_name": "发明名称",
        "biz_patent_col_no": "专利编号",
        "biz_patent_item1_name": "低密度工程用水泥基复合材料及其生产方法",
        "biz_patent_item1_no": "HK30127477",
        "biz_patent_item2_name": "轻质混凝土",
        "biz_patent_item2_no": "HK30112993",
        "iso_desc": "ISO 认证：由第三方机构审核，确保管理体系符合国际标准。",
        "patent_desc": "专利：由政府授权，保障技术或设计的独占使用权。",
        "pqm_title": "预制件质量管理",
        "pqm_desc": "我们以严谨的流程确保每一件预制构件的品质。从原材料检验、工厂生产到现场安装，均遵循国际及本地标准，并设有多重检测环节。透过智能化设备与精细化监控，我们确保产品尺寸准确、性能稳定，为合作伙伴提供可靠、安全、可持续的建筑解决方案。",
        "iso14001_text": "ISO 14001:2015<br>证书编号：CC 5665",
        "iso9001_text": "ISO 9001:2015<br>证书编号：CC 1538",
        "three_inspection_title": "三检制度",
        "three_inspection_desc": "鸿辉品检部对所有产品进行严密监察，确保交付客户的均为优质产品。公司全面推行「三检制度」—— 自检、复检及专检，以保障质量稳定。生产部与品质组负责自检及复检，而中山办则由总公司委派，每周前往东莞厂进行专检，形成多层次的质量把关机制。",
        "insp_self": "自检 (生产部)",
        "insp_re": "复检 (品质组)",
        "insp_special": "专检 (中山办)",
        "traceability_title": "一行交一行",
        "traceability_desc": "鸿辉以“一行交一行”为原则，透过 QR Code 全程追踪生产流程。从铁笼捆扎、模具安装及浇注石矢，到修补工序及成品检验，每一步均有记录，确保质量与进度。若成品日后出现问题，系统可追溯至相关生产工人及验收人员，方便跟进。"
    },
};

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('site_lang') || 'zh';
    updatePageLanguage(savedLang);
});

function switchToEnglish() {
    updatePageLanguage('en');
}

function switchToChinese() {
    updatePageLanguage('zh');
}

function switchToSimplified() {
    updatePageLanguage('cn');
}

function updatePageLanguage(lang) {
    localStorage.setItem('site_lang', lang);
    if (lang === 'en') {
        document.documentElement.lang = 'en';
    } else if (lang === 'cn') {
        document.documentElement.lang = 'zh-CN';
    } else {
        document.documentElement.lang = 'zh-HK';
    }

    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
             if (translations[lang][key].includes('<')) {
                el.innerHTML = translations[lang][key];
            } else {
                el.innerText = translations[lang][key];
            }
        }
    });

    const btnEn = document.querySelector('.btn-en');
    const btnZh = document.querySelector('.btn-zh');
    
    // Update active class for buttons
    // We will clean up the button classes in HTML to be easy to select
    if (document.querySelectorAll('.lang-btn').length > 0) {
        document.querySelectorAll('.lang-btn').forEach(btn => {
            const text = btn.textContent.trim();
            if (text === 'EN') {
                if (lang === 'en') btn.classList.add('active');
                else btn.classList.remove('active');
            } else if (text === '繁' || text === '中') {
                if (lang === 'zh') btn.classList.add('active');
                else btn.classList.remove('active');
            } else if (text === '简') {
                if (lang === 'cn') btn.classList.add('active');
                else btn.classList.remove('active');
            }
        });
    }

    // Update ISO images in sustainability.html
    const iso14001Img = document.getElementById('img-iso14001');
    const iso9001Img = document.getElementById('img-iso9001');
    
    if (iso14001Img && iso9001Img) {
        if (lang === 'en') {
            iso14001Img.src = 'img/quality-management/quality-certification/img_quality_photo01.jpg';
            iso9001Img.src = 'img/quality-management/quality-certification/img_quality_photo02.jpg';
        } else {
            iso14001Img.src = 'img/quality-management/quality-certification/img_quality_photo01.jpg';
            iso9001Img.src = 'img/quality-management/quality-certification/img_quality_photo02.jpg';
        }
    }

    // Reveal body after language update is complete
    document.documentElement.classList.remove('lang-en-pending');
    document.documentElement.classList.remove('lang-update-pending');
}
